[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules']
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200
verbosity = 3

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
bsc = "${BSC_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
estar_testnet = "${ESTAR_TESTNET_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
fantom = { key = "${FTMSCAN_API_KEY}" }
avalanche = { key = "${SNOWTRACE_API_KEY}" }